### ISSUE TITLE
Production prompt and seeder creation

### ISSUE THREAD

**Issue by marickvantuil** [michaeldyrynda/nomad#10]
First of all, thanks for creating this package. It works great and we currently use it for a handful of large clients at the company I work for. 🙂

I have some questions about this package:

Is it possible to be prompted before running migrations in the production environment? I assumed this works because Laravel has this feature. If I create an `app.php` file with environment set to production, I get the following error when trying to run migrations:

```
Target [Illuminate\Contracts\Foundation\Application] is not instantiable.
```

Also, how do I create seeders from the command line? When running `make:seeder` it gives the following error:

```
Unable to detect application namespace.
```

Thanks in advance!

**Comment by michaeldyrynda** [comment]
Check out [vagabond](https://github.com/michaeldyrynda/vagabond). This project is set up to let you do these things as a stand-alone app and handles these things for you. 

Let me know how you go with that. I don’t typically use this repo directly, only as a dependency of that project.

**Comment by marickvantuil** [comment]
Thanks. I tried with a fresh Vagabond installation but get the exact same errors.
