### ISSUE TITLE
Running Nomad in windows machine gives error

### ISSUE THREAD

**Issue by siddheshr** [michaeldyrynda/nomad#13]
Trying to using nomad in windows machine 

 `php nomad migrate:fresh`

Above commmand throws below error

 `dir=$(cd "${0%[/\\]*}" > /dev/null; cd "vendor/dyrynda/nomad" && pwd)`
  `if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi`

` "${dir}/nomad" "$@"`
` dir=$(cd "${0%[/\\]*}" > /dev/null; cd "vendor/dyrynda/nomad" && pwd)
if [ -d /proc/cygdrive ]; then
    case $(which php) in
        $(readlink -n /proc/cygdrive)/*)
            # We are in Cygwin using Windows php, so the path must be translated
            dir=$(cygpath -m "$dir");
            ;;
    esac
fi `

` "${dir}/nomad" "$@" `

Above command works properly in mac and linux machine but in window its throwing error

**Comment by michaeldyrynda** [comment]
I'm sorry I can't offer you any help on this, I don't run or have access to a windows machine.
